### ISSUE TITLE
GELF messages should contain agent id metadata

### ISSUE THREAD

**Issue by kroepke** [Graylog2/collector#10]
Similar to how radio nodes send their input and node id as metadata (gl2_source_radio reserved field) agents should also identify themselves to allow tracing messages back (and allow to group message volumes by agent in a later version).

**Comment by bernd** [comment]
So I will add the following:

1. `gl_source_collector` - contains the collector-id
1. `gl_source_collector_input` - contains the input id, currently from the config file.

Objections?

**Comment by dennisoelkers** [comment]
:+1:
