### ISSUE TITLE
Decide which log framework to use

### ISSUE THREAD

**Issue by bernd** [Graylog2/collector#11]
logback or log4j.

Also create example configuration file.

**Comment by joschi** [comment]
Log4j is currently transitively pulled in by SIGAR while Logback is being pulled in explicitly. The logging framework not being used (and of course JUL, too) should be bridged: http://www.slf4j.org/legacy.html

**Comment by joschi** [comment]
After some internal discussion, we decided to go with [Apache Log4j 2](https://logging.apache.org/log4j/2.x/).
