### ISSUE TITLE
Needs documentation for Windows

### ISSUE THREAD

**Issue by drewmmiranda** [Graylog2/collector#19]
1. What are the dependency requirements? (through trial and error found it asks for JDK vs. Client Java)
2. Instructions for installation, can be as simple as
    1. Install JDK
    2. run command line etc
    3. create config file
3. Need documentation on WHERE config files live, where log files live.
4. NXLog install notes as a point of reference http://nxlog.org/node/295#quickstart_windows

**Comment by bernd** [comment]
Thanks for the report! We started with the Collector documentation here: http://docs.graylog.org/en/1.1/pages/collector.html

I will keep this open until all your suggestions have been implemented.

**Comment by drewmmiranda** [comment]
This looks great! Thanks!

**Comment by jalogisch** [comment]
collector is deprecated - we will not continue this documentation.
