### ISSUE TITLE
Multiline log message support via REGEX pattern

### ISSUE THREAD

**Issue by drewmmiranda** [Graylog2/collector#21]
Some application logs have a single log entry on multiple lines. It won't be helpful to have the log lines shipped as separate messages and should be treated as a single message.

**Comment by trobers** [comment]
It is possible. Show this example:

file-xyz {
  type = "file"
    path = "/opt/dir/nextdir/agent.log"  
    content-splitter = "PATTERN"
    content-splitter-pattern = "^\\d{4}-\\d{2}-\\d{2}"
}

**Comment by drewmmiranda** [comment]
Will test this out, thanks!
