### ISSUE TITLE
Defining custom field in the message

### ISSUE THREAD

**Issue by nilroy** [Graylog2/collector#22]
I wanted top set custom fields like "facility" and "environment" while sending the logs to graylog. How do I do that using the unix version of collector.

**Comment by bernd** [comment]
This is currently not possible. Adding feature label.

**Comment by drewmmiranda** [comment]
This probably isn't terribly helpful, but a shortterm work around could be to add the static fields to the input on the GL server itself. Although the downside is that you would need a separate input per custom fields.

**Comment by nilroy** [comment]
Thanks. Probably I shall try implementing the workaround. But would it be possible to add this feature sometime in future?

**Comment by bernd** [comment]
@nilroy This feature is incoming: https://github.com/Graylog2/collector/pull/45
