### ISSUE TITLE
Add support for wildcards for file input configuration

### ISSUE THREAD

**Issue by bernd** [Graylog2/collector#24]
It can be useful to support wildcards/globbing for file names in file input. This makes it easy to collect generated files and also to avoid excessive configuration if you have a lot of files. (i.e. `/var/log/apache2/*.log` or `/var/log/apps/**/*.log`)

**Comment by drewmmiranda** [comment]
This is a must have for sure. Some log files will never have the same name (See IIS log rotation, by default creates a log per day or hour with timestamps as the filename) or dynamically generated logs that may be rapidly created and deleted by the application.

**Comment by zexxon** [comment]
Please post this idea to our ideas portal: https://www.graylog.org/product-ideas/

**Comment by drewmmiranda** [comment]
Done! https://graylog.ideas.aha.io/ideas/GL2E-I-395

Thanks!
