### ISSUE TITLE
leave filed name as original

### ISSUE THREAD

**Issue by andreaconsadori** [Graylog2/collector#29]
previously i use nxlog to send gelf syslog and it correctly send filed like EventID with filed name "EventID" while graylog collector change this in "event_id" and broke existend correlation rules

**Comment by bernd** [comment]
We do not strive for nxlog compatibility regarding field names. Other products might send the windows event id with a different name, so we cannot make it compatible with all other solutions anyway. Sorry.

**Comment by andreaconsadori** [comment]
but EventID is the original source name, what i ask is not to change the original event field name

 


Date: Wed, 17 Jun 2015 02:08:22 -0700

**Comment by joschi** [comment]
The attribute "event_id" is consistent with other GELF attribute names that are using lower case with underscore (as opposed to CamelCase). If you want to rename the attribute, you can do so with an extractor on the Graylog Collector input: http://docs.graylog.org/en/1.1/pages/extractors.html
