### ISSUE TITLE
3rd party package

### ISSUE THREAD

**Issue by andreaconsadori** [Graylog2/collector#31]
create msi/exe for windows with java embedded inside if possible or a java-less agent.
due to java insecurity some customer have policy that block java installation.
also create rpm and deb for linux installation

**Comment by bernd** [comment]
Please refer to the following feature request and issues for Windows and Linux packaging.

* https://graylog.ideas.aha.io/ideas/GL2E-I-396
* https://github.com/Graylog2/collector/issues/18
* https://github.com/Graylog2/collector/issues/32
