### ISSUE TITLE
using collector for forwarding syslog messages: no facility nor level is shown in graylog server

### ISSUE THREAD

**Issue by plt-sun** [Graylog2/collector#36]
i want to use graylog collector for forwarding my syslog messages ( and some other logfiles too). all seems fine, but in graylog server all messages come with facility "6" and no level is shown. 
if i send syslog messages directly by port 514 to graylog, graylog server shows me facilty and level correct.
need i some additional filters or plugins ??

**Comment by bernd** [comment]
The collector treats the syslog file like any other log file and thus does not know about the facility and level.

If you just want to forward syslog to Graylog, it might be easier to create a syslog input and configure your local syslog server to forward to Graylog.

http://docs.graylog.org/en/1.1/pages/sending_data.html#syslog

When configured like this, Graylog server will receive the full syslog message and can parse the facility and level correctly.

**Comment by plt-sun** [comment]
ok, first i used syslog input from graylog server, but then i need some other application log files additional to log. i thougt it would be easier to do this with one piece of software and configuration (only collector). you are right, i went back to syslog input for my syslog data and additional collector for other application logfiles.
