### ISSUE TITLE
documentation: setting reader- or poll-intervall

### ISSUE THREAD

**Issue by plt-sun** [Graylog2/collector#37]
Here is some question for documentation....
When i start graylog collector, i see for each log file reader-intervall ='100' What this means? seconds, milliseconds?
can i set reading-interval for my logfiles in config/collector.conf?
in colector.conf.example i see in the windows section: poll-interval = 1s. Can i use this also for other log entries in conf file?

**Comment by bernd** [comment]
This is the reader interval in milliseconds. It can be configured with `reader-interval = 100ms`. The setting will be documented once #25 is done.

**Comment by bernd** [comment]
Configuration example:

```
inputs {
  test-log {
    type = "file"
    path = "/var/log/test.log"
    reader-interval = "100ms"
  }
}
```

**Comment by plt-sun** [comment]
ok, setting works.
