### ISSUE TITLE
windows collector 0.2.4 log transfer to the server broken?

### ISSUE THREAD

**Issue by Dominik81** [Graylog2/collector#39]
Windows Graylog Collector 0.2.4 on Windows2008R2std.x64SP1 & Java 1.8.0_45

__config:__
```
server-url = "http://server:no default port/"

message-buffer-size = 128

inputs {
 win-eventlog-application {
    type = "windows-eventlog"
    source-name = "Application"
    poll-interval = 1s
  }
  win-eventlog-system {
    type = "windows-eventlog"
    source-name = "System"
    poll-interval = 1s
  }
  win-eventlog-security {
    type = "windows-eventlog"
    source-name = "Security"
    poll-interval = 1s
  }
}

outputs {
  gelf-udp {
    type = "gelf"
    host = "server"
    port = 12204
  }
}
```

__C:\Program Files\graylog-collector-0.2.4\logs\graylog-collector-stderr.yyyy-mm-dd.log__

```
yyyy-mm-dd hh:mm:ss Commons Daemon procrun stderr initialized
Exception in thread "EventLogThread" Exception in thread "EventLogThread" Exception in thread "EventLogThread" java.lang.UnsatisfiedLinkError: org.hyperic.sigar.win32.EventLog.close()V
	at org.hyperic.sigar.win32.EventLog.close(Native Method)
	at org.hyperic.sigar.win32.EventLogThread.run(EventLogThread.java:175)
	at java.lang.Thread.run(Unknown Source)
java.lang.UnsatisfiedLinkError: org.hyperic.sigar.win32.EventLog.close()V
	at org.hyperic.sigar.win32.EventLog.close(Native Method)
	at org.hyperic.sigar.win32.EventLogThread.run(EventLogThread.java:175)
	at java.lang.Thread.run(Unknown Source)
java.lang.UnsatisfiedLinkError: org.hyperic.sigar.win32.EventLog.close()V
	at org.hyperic.sigar.win32.EventLog.close(Native Method)
	at org.hyperic.sigar.win32.EventLogThread.run(EventLogThread.java:175)
	at java.lang.Thread.run(Unknown Source)
```
We installed the collector via script which now works fine even with whitespaces.
There is a connection openend to the server viewable in *netstat* but we don't see any logs incoming from the collector.

If we add an additional log file entry, which worked with 0.2.2, there seems to be somewhat like a memoryleak which gets cleaned up by the garbagecollector from time to time.
__additional config entry__
```
  test-file {
    type = "file"
    path = "C:/ProgramData/testfolder1/testfolder2/Log.txt"
  }
```

**Comment by bernd** [comment]
Thanks for the report!

So you used the `graylog-collector-service.bat` script to install the service? And with that you get those errors on startup?

What indicates a memory leak when you add an additional log file entry?

**Comment by bernd** [comment]
I am able to reproduce this and work on a fix.

**Comment by bernd** [comment]
Found and fixed the issue. Thanks again for the report!

I just released 0.2.5 which has this fix.

**Comment by bernd** [comment]
@Dominik81 Please let me know if you still see the memory problem with the latest version. Thanks!

**Comment by Dominik81** [comment]
@bernd sry for the late reply
0.2.5 works fine now but with the addional config entry we see the following:
The graylog-collector-service-x64 process uses about 70MB of ram which starts growing about 1MB/s until it reaches ~133MB and falls back to ~70MB.

As mentioned before the additional config entry (now more specific):
```
 }
  test-mcafee {
    type = "file"
    path = "C:/ProgramData/McAfee/DesktopProtection/UpdateLog.txt"
  }

```
The logfile looks like that:

```
03.07.2015	11:02:15	INT\admin.accountname	Task wird gestartet: AutoUpdate
....
03.07.2015	11:02:22	INT\admin.accountname	Aktualisierung beendet
