### ISSUE TITLE
"dynamic" memory usage - memoryleak?

### ISSUE THREAD

**Issue by Dominik81** [Graylog2/collector#41]
refering to issue https://github.com/Graylog2/collector/issues/39
@bernd sry for the late reply

0.2.5 works fine now but with the addional config entry we see the following:

The graylog-collector-service-x64 process uses about 70MB of ram which starts growing about 1MB/s until it reaches ~133MB and falls back to ~70MB.

As mentioned before the additional config entry (now more specific):
```
 }
  test-mcafee {
    type = "file"
    path = "C:/ProgramData/McAfee/DesktopProtection/UpdateLog.txt"
  }

```
The logfile looks like that:

```
03.07.2015	11:02:15	domain\admin.accountname	Task wird gestartet: AutoUpdate
....
03.07.2015	11:02:22	domain\admin.accountname	Aktualisierung beendet

**Comment by bernd** [comment]
This looks like regular GC activity. Can you please try with version 0.3.0?

* https://github.com/Graylog2/collector/blob/master/CHANGELOG.md#v030-2015-07-14
* https://packages.graylog2.org/releases/graylog-collector/graylog-collector-0.3.0.tgz
* https://packages.graylog2.org/releases/graylog-collector/graylog-collector-0.3.0.zip

I will close this issue now, please re-open if you still see problems. Thank you!
