### ISSUE TITLE
Support request: Collector not sending messages

### ISSUE THREAD

**Issue by iBobik** [Graylog2/collector#55]
Hi,
I configured it to send messages from text files to remote Graylog instance. Could you please help me diagnose what happens?

My configuration:
```
server-url = "http://x.x.x:5901"
enable-registration = true
collector-id = "janpoboril@webfaction"
inputs {
  wf-frontend {
    type = "file"
    path-glob-root = "/home/xxx/logs/frontend"
    path-glob-pattern = "*.log"
  }
}
outputs {
  gelf-tcp {
    type = "gelf"
    host = "x.x.x"
    port = 5902
  }
  stdout {
    type = "stdout"
  }
}
```
Config of input:
```
recv_buffer_size: 1048576
port: 12201
tls_key_file:
tls_key_password: *******
max_message_size: 2097152
override_source:
bind_address: 0.0.0.0
tls_cert_file:
```
Port is not same because it is translated by Docker hosting Graylog instance.

Heartbeat is working (I can see collector in Gaylog) and in Inputs I can see active connection. I can see messages in stdout from running collector, but they are not send to gelf-tcp output.

I tried "nc x.x.x 5902" (in same environment with the collector) to send somethink to Graylog input and this messages was received and saved successfully. Everything seems collector is not sending messages to TCP.

Thank you for hint :-)

**Comment by bernd** [comment]
Can you show us the input configuration from the Graylog server?

**Comment by bernd** [comment]
Args, sorry. I didn't see the input config in your post...

**Comment by bernd** [comment]
Are you using a "GELF TCP" input on the server?

**Comment by iBobik** [comment]
Aha, it was „Raw TCP” input. I thought it should receive message of every
type, inc GELF, but it will not parse it.

Thanks :-)



Jan Pobořil

2015-08-24 10:12 GMT+02:00 Bernd Ahlers <notifications@github.com>:

**Comment by bernd** [comment]
Thanks for the update! :+1:
