### ISSUE TITLE
Support for GELF UDP output

### ISSUE THREAD

**Issue by russcollier** [Graylog2/collector#59]
By default the output type "gelf" appears to be GELF TCP only. It'd be nice if we could configure a GELF UDP output for the graylog-collector as well.

**Comment by joschi** [comment]
Implementing a UDP-based GELF output isn't too hard.

This being said, the TCP transport for GELF provides some other nice features over UDP (e. g. transport encryption via TLS), so it would be nice to know why you don't want to or can't use it and use GELF UDP instead.

**Comment by russcollier** [comment]
It's mainly because we have a fairly large amount of existing applications in C#/.NET and C++ currently using the gelf4net and gelf4cplus appenders to log to our Graylog server and those logging appenders only use UDP based GELF. So we only had a GELF UDP input configured on our Graylog server since it's the only input we needed.

It's not a huge deal as we simply added a a GELF TCP input to our server to support the collector as well.
