### ISSUE TITLE
Graylog Collector on Windows Server 2012 R2

### ISSUE THREAD

**Issue by gprade** [Graylog2/collector#60]
I tried to install the Graylog Collector with the instruction on http://docs.graylog.org/en/1.2/pages/collector.html#windows. I do all the steps. But if i want execute  bin\graylog-collector-service.bat install GraylogCollector the Batch dont show all the messages it should show, nothing. After that, there is no Service of Graylog in the ControlPanel. The same for bin\graylog-collector-service.bat start GraylogCollector. I use Graylog Collector 0.4.1 on Windows Server 2012 R2 and tried to install in C:\Programme (x86)\GraylogCollector.
What else must i write?

**Comment by joschi** [comment]
Is Java 7 or higher installed on your system and is the `JAVA_HOME` environment variable set correctly? You can check this by running `echo %JAVA_HOME%` in the command window.

**Comment by gprade** [comment]
JAVA_HOME is set to C:\Program Files\Java\jre1.8.0_60
I had installed Java 8 Update 60 (64 Bit)

**Comment by gprade** [comment]
sorry, sorry, sorry. I dont know what i now do diffrent. Now it works. I do a complete reinstall of the collector and it works.

**Comment by joschi** [comment]
@gprade Great, thanks for the update! I'll close this issue now. If anything comes up again, feel free to add a comment and we can reopen the issue.
