### ISSUE TITLE
IIS log parsing issues

### ISSUE THREAD

**Issue by Spikeophant** [Graylog2/collector#62]
Hi, 

  I have read a bit an am under the impression I should be able to wildcard to parse iis logs:
  iis-eventlog-access {
    type = "file"
    source-name="C:\inetpub\logs\LogFiles\W3SVC1\u_ex*.log"
    poll-interval = "1s"
  }

However when I set this in my configuration and attempt to restart the collector I get

[2015-10-01 10:50:45] [info]  [ 1548] Starting service...
[2015-10-01 10:50:47] [error] [ 3624] Failed to start 'GraylogCollector' service
[2015-10-01 10:50:47] [error] [ 3624] The data area passed to a system call is too small.

I'm sure i've missed something somewhere, but if anyone can point me in the right direction I'd appreciate it.

**Comment by bernd** [comment]
You are mixing up configuration values from the file and windows-eventlog inputs. Please check the documentation for details. http://docs.graylog.org/en/1.2/pages/collector.html#input-settings
