### ISSUE TITLE
No message if file input cannot access actual file

### ISSUE THREAD

**Issue by kroepke** [Graylog2/collector#7]
Steps to reproduce:
1) configure file input to read from non-existent file or set permissions to deny access
2) start agent
3) no message about the file is printed, at least not on INFO or higher

Expectation:
Print warning or error message if the file cannot be opened for reading.

**Comment by bernd** [comment]
The collector logs a WARN if a configured file does not exist and it can follow a file once it becomes readable by the process.

**Comment by nugend** [comment]
I have a collector configured against a directory with a pattern like "**/*.log" I started the collector with no files in the directory and then started the system up. Files were subsequently added. No logging input seems to be sent to graylog. Restarting the collector sure enough sees messages start showing up.

Additionally, new files appearing in the directory and appended to do not see their lines sent to graylog either

**Comment by bernd** [comment]
No, that sounds wrong. Can you please open a new issue for this including your collector configuration, Java version and platform you are running on? Thank you!
