### ISSUE TITLE
Allow multiple outputs

### ISSUE THREAD

**Issue by eorochena** [Graylog2/collector#75]
Hi -

It would be nice to have the ability to send outputs to multiple graylog servers

outputs {
//  // GELF output to send messages to a Graylog server. Usually only type, host and port are needed.
//  // The other options are for TLS support and to fine-tune the GELF client library.
  gelf-tcp-primary {
    type = "gelf"
    host = "192.168.1.9"
    port = 12201
 }

  gelf-tcp-secondary {
    type = "gelf"
    host = "192.168.1.10"
    port = 12201
 }

**Comment by joschi** [comment]
@eorochena That's already possible with the Graylog Collector. Simply add those output references to your input(s).

Example:
```
inputs {
  apache-access {
    type = "file"
    path = "/var/log/apache2/access.log"
    outputs = "gelf-tcp-primary,gelf-tcp-secondary"
  }
}

outputs {
  gelf-tcp-primary {
    type = "gelf"
    host = "192.168.1.9"
    port = 12201
  }

  gelf-tcp-secondary {
    type = "gelf"
    host = "192.168.1.10"
    port = 12201
  }
}
```

**Comment by eorochena** [comment]
That's great, but  my only concern is that whenever we lose connection with one of the graylog servers the collector stop sending messages to both locations
