### ISSUE TITLE
Collector registration/heartbeat failing with Graylog 2.0.0 Alpha 5

### ISSUE THREAD

**Issue by gitfrederic** [Graylog2/collector#84]
Using existing (0.4.2) Collector with Graylog 2.0.0 Alpha 5 (with Collector Plugin).

The collector daemon/agent (GELF-TCP output) on log source machine is sending:
```
PUT /system/collectors/[id] HTTP/1.1
User-Agent: Graylog Collector v0.4.2(commit 2609a38)
X-Graylog-Collector-Version: 0.4.2
Content-Type: application/json; charset=UTF-8
Host: [HOST]:12900
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2
Connection: keep-alive
Content-Length: 98

{"node_id":"[NODE_ID]","node_details":{"operating_system":"Linux"}}
```

And is getting back (from Graylog server):
```
HTTP/1.1 404 Not Found
X-Graylog-Node-ID: 0f642f90-a025-4989-9269-737f08a908df
Content-Type: application/json
Date: Sat, 12 Mar 2016 04:31:06 GMT
Content-Length: 50

{"type":"ApiError","message":"HTTP 404 Not Found"}
```

Collector log shows:
```
2016-03-12T05:15:48.935+0000 WARN  [HeartbeatService RUNNING] collector.heartbeat.HeartbeatService - Unable to send heartbeat to Graylog server, result was: 404 - Not Found
```

**Comment by joschi** [comment]
@gitfrederic Thanks for reporting this. Since the collector functionality has been pushed into a plugin in Graylog 2.0.0-alpha.5, the old Graylog Collector is incompatible with that version at the moment. We'll release an updated version of the Graylog Collector in time for Graylog 2.0.0 (possibly for the beta versions).

**Comment by Buzut** [comment]
Wooow, I don't think I got it… I installed the 2.0 graylog from the .deb provided on this page. So far so good, the install goes well. Then and want to register a collector and I understand that collectors that used to work with pre 2.0 versions aren't compatible. But on the ("lastest" collector)[http://docs.graylog.org/en/latest/pages/collector.html] documentation, the link to the deb file is the same as the one given in "stable".  Obviously I end up with the `HeartbeatService RUNNING] collector.heartbeat.HeartbeatService - Unable to send heartbeat to Graylog server, result was: 404 - Not Found` error. Is there a way to get the compatible collector? (or did I miss something…?)

**Comment by joschi** [comment]
@Buzut The Graylog Collector is currently incompatible with the alphas/betas/release candidates of Graylog 2.0.0 but will be updated for the final release of Graylog 2.0.0.

**Comment by Buzut** [comment]
@joschi Ok. Waiting for the GA then :)

**Comment by rompic** [comment]
tried to update the collector but still get the same error, has this already been released?
