### ISSUE TITLE
Open source windows binaries

### ISSUE THREAD

**Issue by Spitfire1900** [Graylog2/collector#88]
The Windows binaries are having issues on our end when using IBM's jdk instead of Oracle's. It would be easier to address these issues if the binaries were open sourced.

**Comment by joschi** [comment]
@Spitfire1900 There are absolutely no proprietary parts in the artifacts of Graylog Collector.

For which parts are you unable to find the source code?

**Comment by Spitfire1900** [comment]
I was interested in viewing the source code of  bin/windows/graylog-collector-service-x64.exe

Though the problem that we were having that prompted this to be open would be addressed with  #89. The service would not start correctly because a 64-bit jvm.dll was being passed to a 32-bit service as IBM JDK's output of java -version is not the same as Oracle's.

**Comment by joschi** [comment]
@Spitfire1900 Those executable files have been taken from the Apache Commons Daemon project, specifically from https://commons.apache.org/proper/commons-daemon/binaries.html

**Comment by Spitfire1900** [comment]
Thanks, that clarifies things.
