### ISSUE TITLE
release .deb for latest release

### ISSUE THREAD

**Issue by rompic** [Graylog2/collector#92]
The latest.deb available for ubuntu is still Version: 0.4.2-1. please release version 0.5 as .deb.
Thanks,
Roman

**Comment by joschi** [comment]
@rompic There won't be a release of the Graylog Collector anymore. Sorry.

If you want to use Graylog Collector 0.5.0, please use [the tar-balls referenced in the README](https://github.com/Graylog2/collector/tree/master#binary-download).
